# OSS FOUNDATIONS: Git Setups

# listInstalledBinaries
# listSupportedVersionsRange
# listRecommendedVersion

alias gitExists='which git'
alias gE='gitExists'
alias gitVersion='git --version'
alias gV='gitVersion'
alias gitConfigs='git config --list'
alias gCfg='gitConfigs'

# OSS FOUNDATIONS: Git Solo Local: LEVEL 1

alias gitClone='git clone'
alias gCl='gitClone'
alias gitInit='git init'
alias gI='gitInit'
alias gitAdd='git add'
alias gA='gitAdd'
alias gitCommit='git commit'
alias gCom='gitCommit'
alias gitPush='git push'
alias gPsh='gitPush'
alias gitStash='git stash'
alias gSta='gitStash'
alias gitStatus='git status'
alias gSt='gitStatus'
alias gitApply='git apply'
alias gAp='gitApply'

# OSS FOUNDATIONS: Git Solo Local: LEVEL 2

# OSS FOUNDATIONS: Git Solo Remote: LEVEL 1

# OSS FOUNDATIONS: Git Solo Remote: LEVEL 2

# OSS FOUNDATIONS: Team Dev Using Git + Github.com: LEVEL 1

# OSS FOUNDATIONS: Team Dev Using Git + Github.com: LEVEL 2

